Chef/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from .views import views
from .views import booking


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^gallery/', views.gallery_view, name='gallery'),
    url(r'^reservation/', booking.reservation_view, name='booking'),
    url(r'^contact_us', views.contact_us, name='contact_us'),
    url(r'^about_us', views.about_us, name='about-us'),
    url('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^food/', include('food.urls', namespace='food')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from . import views, profile


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^reset_password', views.reset_password_view, name='reset_password'),
    url(r'^profile/$', profile.profile_view, name='profile'),
    url(r'^change_password/$', profile.change_password_view, name='change_password'),
    url(r'^logout/$', views.logout_view, name='logout')
 ]

food/urls.py
from django.conf.urls import url
from . import views
from Chef.views import cart


urlpatterns = [
    url(r'^menu_food/$', views.menu_food_view, name='menu_food'),
    url(r'^detail/(?P<slug>[-\w]+)-(?P<rid>\w+)$', views.detail_food_view, name='detail'),
    url(r'^add/cart/$', cart.add_to_cart_view, name='add_to_cart'),
    url(r'^cart/$', cart.cart_view, name='cart'),
    url(r'cart/delete/$', cart.cart_item_delete_view, name='delete_item'),
    url(r'^cart/checkout/$', cart.checkout_view, name='checkout')

]

Chef/models.py
from django.db import models
from django.forms import ModelForm
from account.models import Customer


class Gallery(models.Model):
    gallery_img = models.ImageField(upload_to='food/galley_images')

    # def __str__(self):
    #     pass


class Table(models.Model):
    TABLE = (
        ('1', 'Inside'),
        ('2', 'Outside'),
    )
    seats = models.IntegerField(default=1)
    max_size = models.IntegerField(default=2)
    locate_table = models.CharField(max_length=1, choices=TABLE, blank=True)


# class TableForm(ModelForm):
#     class Meta:
#         model = Table
#         fields = ['seats', 'max_size', 'locate_table']


class Event(models.Model):
    PARTY_SIZE = (
        ('1', 'Less than 5'),
        ('2', 'Less than 10'),
        ('3', 'More than 10'),
    )
    # event = models.CharField()
    party = models.CharField(max_length=1, blank=False, choices=PARTY_SIZE)
    event_name = models.CharField(max_length=50, blank=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        return self.event_name


# class EventForm(ModelForm):
#     class Meta:
#         model = Event
#         fields = ['party', 'event_name']


class Booking(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    event = models.ForeignKey(Event,  on_delete=models.CASCADE)
    number_of_people = models.IntegerField(default=1)
    dining_date = models.DateField()
    dining_time = models.TimeField()

    def __str__(self):
        return self.Customer.username

    def save(self, *args, **kwargs):
        created = self.pk is None
        super(Booking, self).save(*args, **kwargs)
        if created:
            Event.objects.create(event=self)
            Table.objects.create(table=self)


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    email = models.EmailField()
    message = models.TextField()


class AboutUs(models.Model):
    subject = models.CharField(max_length=100, blank=True)
    content = models.TextField()
    picture = models.ImageField()

Chef/forms.py
from django import forms
from Chef.models import Booking
from datetimewidget.widgets import DateWidget, TimeWidget, DateTimeWidget
# from Chef.widgets import DateWidget


class ReservationForm(forms.Form):
    first_name = forms.CharField(max_length=502)
    last_name = forms.CharField(max_length=50)
    phone_number = forms.CharField(max_length=15)
    number_of_people = forms.CharField(max_length=3)
    dining_time = forms.TimeField(widget=TimeWidget)
    dining_date = forms.DateTimeField(widget=DateWidget)
    party = forms.CharField(max_length=5)
    event_name = forms.CharField(max_length=100)
    # seats = forms.CharField(max_length=3)
    # max_size = forms.CharField(max_length=3)
    locate_table = forms.CharField(max_length=1)

    # class Meta:
    #     model = Booking
    #     fields = ('dining_date', 'dining_time')
    #
    dateOptions = {
            'format': 'dd/mm/yyyy',
            'auto close': True,
            'showMeridian': True
        }
    widgets = {
        # Use localization and bootstrap 4
        'dining_date':  DateWidget(options=dateOptions, attrs={'id': 'date_dining'})

        }

    timeOptions = {
        'format': 'HH:ii P',
        'auto close': True,
        'ShowMeridian': True
    }

    widgets = {
        'dining_time': TimeWidget(options=timeOptions, attrs={'id': 'time_dining'})
    }
    # widgets = {
    #         # Use localization and bootstrap 4
    #         'dining_date':  DateTimeWidget(attrs={'id': 'date_dining'}, usel10n=True, bootstrap_version=4)
    #
    #     }


class EventForm(forms.Form):
    party = forms.CharField(max_length=5)
    event_name = forms.CharField(max_length=100)


class TableForm(forms.Form):
    seats = forms.CharField(max_length=3)
    max_size = forms.CharField(max_length=3)
    locate_table = forms.CharField(max_length=1)


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

Chef/views/booking.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from Chef.models import Booking, Table
from account.models import Customer
from Chef.forms import ReservationForm, EventForm, TableForm


def reservation_view(request):
    user = request.user
    if request.POST:
        form = ReservationForm(request.POST)
        data = form.cleaned_data

        if form.is_valid():
            print("here1")
            # if data['seats'] < data['number_of_people'] or not (data['number_of_people'].is_digit()):
            #     return render(request, 'Chef/reservation.html', {'validation': 'not valid'})
            booking = Booking.objects.create(number_of_people=data['number_of_people'],
                                             seats=data['seats'],
                                             dining_date=data['dining_date'],
                                             dining_time=data['dining_time'],
                                             )
            # booking.set_table(seats=data['seats'],
            #                   locate_table=data['locate_table'],
            #                   max_size=data['max_size'])
            # booking.set_event(party=data['party'],
            #                   event_name=data['event_name'])
            booking.save()
            print("here2")
            return render(request, 'Chef/reservation.html', {'Ok': True})

        else:
            return render(request, 'Chef/reservation.html', {'form': form})
    else:
        data = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'phone_number': user.phone_number
        }

        return render(request, 'Chef/reservation.html', {'form': ReservationForm(initial=data)})

Chef/views/cart.py
from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from food.models import Food, FoodQuantity, Order


def add_to_cart_view(request):
    food = Food.objects.get(id=request.POST.get('food-id'))
    quantity = int(1)
    if request.session.get('foods'):
        request.session['foods'].append({'name': food.name,
                                         'food_id': food.id,
                                         'price': food.price,
                                         'picture': food.picture_food.url,
                                         'quantity': quantity,
                                         })
        # for key, value in request.session.items():
        #     print('{} => {}'.format(key, value))

        subtotal = 0
        shipping = 5
        # total = 0

        for food in request.session['foods']:
            subtotal += food['price'] * food['quantity']
            total = subtotal + shipping

            request.session['subtotal'] = subtotal
            request.session['total'] = total
        request.session.save()
    else:
        request.session['foods'] = [{'name': food.name,
                                    'food_id': food.id,
                                    'price': food.price,
                                    'picture': food.picture_food.url,
                                    'quantity': quantity,
                                     }]

        subtotal = 0
        shipping = 5
        # total = 0

        for food in request.session['foods']:
            subtotal += food['price'] * food['quantity']
            total = subtotal + shipping

            request.session['subtotal'] = subtotal
            request.session['total'] = total
        request.session.save()
    return HttpResponseRedirect(reverse('food:cart'))


def cart_view(request):
    if request.session.get('foods'):
        if request.POST:
            # subtotal = request.POST.get('subtotal')
            # total = request.POST.get('total')
            # fid = request.POST.get('food-id')
            # for key, value in request.session.items():
            #     print('{} => {}'.format(key, value))
            # for food in request.session['foods']:
            #     food['quantity'] = (request.POST[food['food_id']])
            subtotal = 0
            shipping = 5
            # total = 0
            for food in request.session['foods']:
                subtotal += food['price'] * food['quantity']
                total = subtotal + shipping

                request.session['subtotal'] = subtotal
                request.session['total'] = total
            request.session.save()
    return render(request, 'Chef/cart.html')


def cart_item_delete_view(request):
    # //Delete items one by one
    if request.session.get('foods'):
        subtotal = request.session['subtotal']
        shipping = 5
        fid = request.POST.get('food-id')
        for food in request.session['foods']:
            if food['food_id'] == int(fid):
                subtotal -= food['price'] * int(food['quantity'])
                request.session['foods'].remove(food)
                request.session['subtotal'] = subtotal
                request.session['total'] = subtotal + shipping
            request.session.save()
        return HttpResponseRedirect(reverse('food:cart'))


def cart_delete_view(request):
    # /// Delete all orders in cart
    if request.session.get('foods'):
        del request.session['foods']

    return HttpResponseRedirect(reverse('food:menu_food'))
# def cart_view(request):
#     if request.session.get('foods'):
#         print("here111")
#         if request.POST:
#             print("here222")
#             for food in request.session['foods']:
#                 print(food['quantity'])
#                 food['quantity'] = (request.POST['food-' + str(food['food_id'])])
#             subtotal = 0
#             salestax = 0
#             shiping = 5
#             total = 0
#             for food in request.session['foods']:
#                 subtotal += food['price'] * food['quantity']
#                 salestax += subtotal * 0.05
#                 total += subtotal + shiping + salestax
#                 request.session['subtotal'] = subtotal
#                 request.session['total'] = total
#
#             request.session.save()
#     return render(request, 'Chef/cart.html')


def checkout_view(request):
    if request.user.is_authenticated():
        if request.session.get('foods'):
            if request.POST:
                order = Order.objects.create(customer=request.user, status='PEN')
                for session_food in request.session['foods']:
                    print(session_food['quantity'])
                    food_quantity = FoodQuantity.objects.create(food_id=session_food['food_id'],
                                                                quantity=session_food['quantity']
                                                                )
                    order.foods.add(food_quantity)
                    print(order)
                del request.session['foods']
                return render(request, 'food/checkout_list.html', {'msg': 'Ok'})
            else:
                return render(request, 'food/checkout_list.html')
    else:
        # if request.is_ajax():
            data = {
                'message': "You have to login !!!"
            }
            return JsonResponse(data)
            # return HttpResponseRedirect(reverse('account:login'), {'ok':ok})

Chef/views/views.py
from django.shortcuts import render
from Chef.models import Gallery, Contact
from Chef.forms import ContactForm


def home(request):
    return render(request, 'Chef/index.html')


def gallery_view(request):
    img = Gallery.objects.all()
    return render(request, 'Chef/gallery.html', {'img_gallery': img})


def contact_us(request):
    if request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            all_contact = Contact.objects.create(first_name=data['first_name'], last_name=data['last_name'],
                                                 email=data['email'], message=data['message'])
            all_contact.save()
            print("end")
            return render(request, 'Chef/ContactUs.html', {'success': True})
        else:

            return render(request, 'Chef/ContactUs.html', {'error': True, 'form': form})

    else:
        return render(request, 'Chef/ContactUs.html', {'form': ContactForm()})


def about_us(request):
    return render(request, 'Chef/About Us.html')

Chef/templates/Chef/About Us.html
{% extends 'Chef/base.html' %}
{% load static %}


{% block slider %}
    <!--================Banner Area =================-->
    <section class="banner_area">
        <div class="container">
            <div class="banner_content">
                <h4>About Us</h4>
                <a href="#">Home</a>
                <a class="active" href="#">About Us</a>
            </div>
        </div>
    </section>
        <!--================End Banner Area =================-->

    <section class="about_us_content">
            <div class="container">
                <div class="row about_inner_item">
                    <div class="col-md-6">
                        <div class="about_left_content">
                            <h4>Since 1962</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typeting, remaining essentially unchanged.</p>
                            <ul>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> The standard chunk of Lorem Ipsum used.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> Sed ut perspiciatis unde omnis iste natus error.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> At vero eos et accusamus et iusto odio dignissimos.</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="about_right_image">
                            <img src="{% static 'chef/images/about-item/about-item-1.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="about_single_content">
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sture there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
                        </div>
                    </div>
                </div>
                <div class="row about_inner_item">
                    <div class="col-md-6">
                        <div class="about_right_image">
                            <img src="{% static 'chef/images/about-item/about-item-2.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="about_left_content">
                            <h4>About Our Menu</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typeting, remaining essentially unchanged.</p>
                            <ul>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> The standard chunk of Lorem Ipsum used.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> Sed ut perspiciatis unde omnis iste natus error.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> At vero eos et accusamus et iusto odio dignissimos.</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="about_single_content">
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sture there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
                        </div>
                    </div>
                </div>
                <div class="row about_inner_item">
                    <div class="col-md-6">
                        <div class="about_left_content">
                            <h4>Best Services</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typeting, remaining essentially unchanged.</p>
                            <ul>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> The standard chunk of Lorem Ipsum used.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> Sed ut perspiciatis unde omnis iste natus error.</a></li>
                                <li><a href="#"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> At vero eos et accusamus et iusto odio dignissimos.</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="about_right_image">
                            <img src="{% static 'chef/images/about-item/about-item-3.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="about_single_content">
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sture there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock slider %}

Chef/templates/Chef/cart.html
{% extends 'Chef/base.html' %}
{% load static %}

{% block slider %}
     <!--================Banner Area =================-->
        <section class="banner_area">
            <div class="container">
                <div class="banner_content">
                    <h4>Your Cart</h4>
                    <a href="#">Home</a>
                     <a class="active" href="#">Cart</a>
                </div>
            </div>
        </section>
    <!--================End Banner Area =================-->

<head>
    <meta charset="UTF-8">
    <title>Delicious Shopping Cart</title>
    <link rel="stylesheet" href="{% static 'food/cart/css/reset.min.css' %}">
    <link rel='stylesheet' href='{% static 'food/cart/css/jquery-ui.css' %}'>
    <link rel="stylesheet" href="{% static 'food/cart/css/style.css' %}">
    <script src="{% static 'food/cart/js/prefixfree.min.js' %}"></script>

</head>
<body>
<!-- partial:index.partial.html -->
    <div class="header">
        <p>
            "I say let the world go to hell, but I should always have my tea."
        </p>
        <p>
            ― Fyodor Dostoyevsky, Notes from Underground
        </p>
    </div>

<div class="cart-container">

    <ul class="cart">
       {% if request.session.foods %}
        <form action="{% url 'food:delete_item'  %}" method="POST">{% csrf_token %}
        {%  for food in request.session.foods %}
        <li class="product" data-price="{{ food.price}}" data-quantity="{{ food.quantity }}" >
            <div class="product-preview">
                <div class="thumbnail">
                    <img class="image" src="{{ food.picture }}" />
                </div>
                <div class="product-paper">
                    <div class="product-name">
                        {{ food.name }}
                    </div>
                    <div class="product-price">
                        $ {{ food.price}}
                    </div>
                </div>
            </div>
            <div class="product-quantity">
                x{{food.quantity}}
{#                <input type="number" style="{width:7px; height:6px}" name="food-{{ food.food_id }}"  value="x{{ food.quantity }}" min="1">#}

            </div>
            <div class="product-interactions">
                <div class="button plus">
                    +
                </div>
                <div class="button minus">
                    -
                </div>
                <input  type="hidden" name="food-id" value="{{ food.food_id}}"/>
                <input  class="button del" type="submit" value="x" />
{#                <div class="button del">#}
{#                    <input  class="button del" type="submit" value="x" />#}
{#                </div>#}
            </div>
        </li>
        {% endfor %}
        </form>
        </ul>

    </div>
    <table class="bill">
        <tr class="subtotal">
            <td class="label">
              Subtotal :
            </td>
            <td class="value">
              $ {{  request.session.subtotal }}
            </td>
        </tr>

        <tr>
            <td class="label">
                Shipping :
            </td>
            <td class="value">
                $ 5.00
            </td>
        </tr>
        <tr class="total">
            <td class="label">
                Total :
            </td>
            <td class="value">
          $ {{ request.session.total }}
        </td>
        </tr>
    </table>
    <div class="actions">
        <div class="big-button go">
            <a id = 'chk'  href="{% url 'food:checkout' %}"> Get them ! </a>
        </div>
{#        <div id="dialog">#}
{#            <p><a href="{% url 'account:login' %}"> Go to Login Page</a></p>#}
{#        </div>#}
    </div>

    {% else %}

    <section class="cart_area">
        <div class="container-cart">
            <div class="cart_content">
                <h4>empty</h4>
{#                    <a href="#">Home / </a>#}
{#                    <a class="active" href="#">Your Orders</a>#}
            </div>
        </div>
    </section>
    {% endif %}

    <div class="actions">
        <div class="big-button return">
            <a href="{% url 'food:menu_food' %}"> Return to shop</a>
        </div>
    </div>
{#    <div class="actions">#}
{#        <div>#}
{#            <a href="{% url 'food:checkout' %}"> Check out Orders</a>#}
{#        </div>#}
{##}
{#    </div>#}
    <!-- partial -->
    <script src='{% static 'food/cart/js/jquery.min.js' %}'></script>
    <script src='{% static 'food/cart/js/jquery-ui.min.js' %}'></script>
    <script  src="{% static 'food/cart/js/script.js' %}"></script>
    <script  src="{% static 'food/cart/js/message.js' %}"></script>

    </body>
    </html>
    {% endblock slider %}