Chef/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from .views import views
from .views import booking


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^gallery/', views.gallery_view, name='gallery'),
    url(r'^reservation/', booking.reservation_view, name='booking'),
    url(r'^contact_us', views.contact_us, name='contact_us'),
    url(r'^about_us', views.about_us, name='about-us'),
    url('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^food/', include('food.urls', namespace='food')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.conf.urls import url
from . import views
from Chef.views import cart


urlpatterns = [
    url(r'^menu_food/$', views.menu_food_view, name='menu_food'),
    url(r'^detail/(?P<slug>[-\w]+)-(?P<rid>\w+)$', views.detail_food_view, name='detail'),
    url(r'^add/cart/$', cart.add_to_cart_view, name='add_to_cart'),
    url(r'^cart/$', cart.cart_view, name='cart'),
    url(r'cart/delete/$', cart.cart_item_delete_view, name='delete_item'),
    url(r'^cart/checkout/$', cart.checkout_view, name='checkout')

]

Chef/models.py
from django.db import models
from django.forms import ModelForm
from account.models import Customer


class Gallery(models.Model):
    gallery_img = models.ImageField(upload_to='food/galley_images')

    # def __str__(self):
    #     pass


class Table(models.Model):
    TABLE = (
        ('1', 'Inside'),
        ('2', 'Outside'),
    )
    seats = models.IntegerField(default=1)
    max_size = models.IntegerField(default=2)
    locate_table = models.CharField(max_length=1, choices=TABLE, blank=True)


# class TableForm(ModelForm):
#     class Meta:
#         model = Table
#         fields = ['seats', 'max_size', 'locate_table']


class Event(models.Model):
    PARTY_SIZE = (
        ('1', 'Less than 5'),
        ('2', 'Less than 10'),
        ('3', 'More than 10'),
    )
    # event = models.CharField()
    party = models.CharField(max_length=1, blank=False, choices=PARTY_SIZE)
    event_name = models.CharField(max_length=50, blank=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        return self.event_name


# class EventForm(ModelForm):
#     class Meta:
#         model = Event
#         fields = ['party', 'event_name']


class Booking(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    event = models.ForeignKey(Event,  on_delete=models.CASCADE)
    number_of_people = models.IntegerField(default=1)
    dining_date = models.DateField()
    dining_time = models.TimeField()

    def __str__(self):
        return self.Customer.username

    def save(self, *args, **kwargs):
        created = self.pk is None
        super(Booking, self).save(*args, **kwargs)
        if created:
            Event.objects.create(event=self)
            Table.objects.create(table=self)


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    email = models.EmailField()
    message = models.TextField()


class AboutUs(models.Model):
    subject = models.CharField(max_length=100, blank=True)
    content = models.TextField()
    picture = models.ImageField()

Chef/forms.py
from django import forms
from Chef.models import Booking
from datetimewidget.widgets import DateWidget, TimeWidget, DateTimeWidget
# from Chef.widgets import DateWidget


class ReservationForm(forms.Form):
    first_name = forms.CharField(max_length=502)
    last_name = forms.CharField(max_length=50)
    phone_number = forms.CharField(max_length=15)
    number_of_people = forms.CharField(max_length=3)
    dining_time = forms.TimeField(widget=TimeWidget)
    dining_date = forms.DateTimeField(widget=DateWidget)
    party = forms.CharField(max_length=5)
    event_name = forms.CharField(max_length=100)
    # seats = forms.CharField(max_length=3)
    # max_size = forms.CharField(max_length=3)
    locate_table = forms.CharField(max_length=1)

    # class Meta:
    #     model = Booking
    #     fields = ('dining_date', 'dining_time')
    #
    dateOptions = {
            'format': 'dd/mm/yyyy',
            'auto close': True,
            'showMeridian': True
        }
    widgets = {
        # Use localization and bootstrap 4
        'dining_date':  DateWidget(options=dateOptions, attrs={'id': 'date_dining'})

        }

    timeOptions = {
        'format': 'HH:ii P',
        'auto close': True,
        'ShowMeridian': True
    }

    widgets = {
        'dining_time': TimeWidget(options=timeOptions, attrs={'id': 'time_dining'})
    }
    # widgets = {
    #         # Use localization and bootstrap 4
    #         'dining_date':  DateTimeWidget(attrs={'id': 'date_dining'}, usel10n=True, bootstrap_version=4)
    #
    #     }


class EventForm(forms.Form):
    party = forms.CharField(max_length=5)
    event_name = forms.CharField(max_length=100)


class TableForm(forms.Form):
    seats = forms.CharField(max_length=3)
    max_size = forms.CharField(max_length=3)
    locate_table = forms.CharField(max_length=1)


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

food/forms.py
from django import forms


class FoodDetailForm(forms.Form):
    name = forms.CharField(max_length=200)
    price = forms.CharField(max_length=5)
    rating = forms.CharField(max_length=3)

Chef/views/booking.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from Chef.models import Booking, Table
from account.models import Customer
from Chef.forms import ReservationForm, EventForm, TableForm


def reservation_view(request):
    user = request.user
    if request.POST:
        form = ReservationForm(request.POST)
        data = form.cleaned_data

        if form.is_valid():
            print("here1")
            # if data['seats'] < data['number_of_people'] or not (data['number_of_people'].is_digit()):
            #     return render(request, 'Chef/reservation.html', {'validation': 'not valid'})
            booking = Booking.objects.create(number_of_people=data['number_of_people'],
                                             seats=data['seats'],
                                             dining_date=data['dining_date'],
                                             dining_time=data['dining_time'],
                                             )
            # booking.set_table(seats=data['seats'],
            #                   locate_table=data['locate_table'],
            #                   max_size=data['max_size'])
            # booking.set_event(party=data['party'],
            #                   event_name=data['event_name'])
            booking.save()
            print("here2")
            return render(request, 'Chef/reservation.html', {'Ok': True})

        else:
            return render(request, 'Chef/reservation.html', {'form': form})
    else:
        data = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'phone_number': user.phone_number
        }

        return render(request, 'Chef/reservation.html', {'form': ReservationForm(initial=data)})

Chef/views/cart.py
from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from food.models import Food, FoodQuantity, Order


def add_to_cart_view(request):
    food = Food.objects.get(id=request.POST.get('food-id'))
    quantity = int(1)
    if request.session.get('foods'):
        request.session['foods'].append({'name': food.name,
                                         'food_id': food.id,
                                         'price': food.price,
                                         'picture': food.picture_food.url,
                                         'quantity': quantity,
                                         })
        # for key, value in request.session.items():
        #     print('{} => {}'.format(key, value))

        subtotal = 0
        shipping = 5
        # total = 0

        for food in request.session['foods']:
            subtotal += food['price'] * food['quantity']
            total = subtotal + shipping

            request.session['subtotal'] = subtotal
            request.session['total'] = total
        request.session.save()
    else:
        request.session['foods'] = [{'name': food.name,
                                    'food_id': food.id,
                                    'price': food.price,
                                    'picture': food.picture_food.url,
                                    'quantity': quantity,
                                     }]

        subtotal = 0
        shipping = 5
        # total = 0

        for food in request.session['foods']:
            subtotal += food['price'] * food['quantity']
            total = subtotal + shipping

            request.session['subtotal'] = subtotal
            request.session['total'] = total
        request.session.save()
    return HttpResponseRedirect(reverse('food:cart'))


def cart_view(request):
    if request.session.get('foods'):
        if request.POST:
            # subtotal = request.POST.get('subtotal')
            # total = request.POST.get('total')
            # fid = request.POST.get('food-id')
            # for key, value in request.session.items():
            #     print('{} => {}'.format(key, value))
            # for food in request.session['foods']:
            #     food['quantity'] = (request.POST[food['food_id']])
            subtotal = 0
            shipping = 5
            # total = 0
            for food in request.session['foods']:
                subtotal += food['price'] * food['quantity']
                total = subtotal + shipping

                request.session['subtotal'] = subtotal
                request.session['total'] = total
            request.session.save()
    return render(request, 'Chef/cart.html')


def cart_item_delete_view(request):
    # //Delete items one by one
    if request.session.get('foods'):
        subtotal = request.session['subtotal']
        shipping = 5
        fid = request.POST.get('food-id')
        for food in request.session['foods']:
            if food['food_id'] == int(fid):
                subtotal -= food['price'] * int(food['quantity'])
                request.session['foods'].remove(food)
                request.session['subtotal'] = subtotal
                request.session['total'] = subtotal + shipping
            request.session.save()
        return HttpResponseRedirect(reverse('food:cart'))


def cart_delete_view(request):
    # /// Delete all orders in cart
    if request.session.get('foods'):
        del request.session['foods']

    return HttpResponseRedirect(reverse('food:menu_food'))
# def cart_view(request):
#     if request.session.get('foods'):
#         print("here111")
#         if request.POST:
#             print("here222")
#             for food in request.session['foods']:
#                 print(food['quantity'])
#                 food['quantity'] = (request.POST['food-' + str(food['food_id'])])
#             subtotal = 0
#             salestax = 0
#             shiping = 5
#             total = 0
#             for food in request.session['foods']:
#                 subtotal += food['price'] * food['quantity']
#                 salestax += subtotal * 0.05
#                 total += subtotal + shiping + salestax
#                 request.session['subtotal'] = subtotal
#                 request.session['total'] = total
#
#             request.session.save()
#     return render(request, 'Chef/cart.html')


def checkout_view(request):
    if request.user.is_authenticated():
        if request.session.get('foods'):
            if request.POST:
                order = Order.objects.create(customer=request.user, status='PEN')
                for session_food in request.session['foods']:
                    print(session_food['quantity'])
                    food_quantity = FoodQuantity.objects.create(food_id=session_food['food_id'],
                                                                quantity=session_food['quantity']
                                                                )
                    order.foods.add(food_quantity)
                    print(order)
                del request.session['foods']
                return render(request, 'food/checkout_list.html', {'msg': 'Ok'})
            else:
                return render(request, 'food/checkout_list.html')
    else:
        # if request.is_ajax():
            data = {
                'message': "You have to login !!!"
            }
            return JsonResponse(data)
            # return HttpResponseRedirect(reverse('account:login'), {'ok':ok})

Chef/views/views.py
from django.shortcuts import render
from Chef.models import Gallery, Contact
from Chef.forms import ContactForm


def home(request):
    return render(request, 'Chef/index.html')


def gallery_view(request):
    img = Gallery.objects.all()
    return render(request, 'Chef/gallery.html', {'img_gallery': img})


def contact_us(request):
    if request.POST:
        form = ContactForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            all_contact = Contact.objects.create(first_name=data['first_name'], last_name=data['last_name'],
                                                 email=data['email'], message=data['message'])
            all_contact.save()
            print("end")
            return render(request, 'Chef/ContactUs.html', {'success': True})
        else:

            return render(request, 'Chef/ContactUs.html', {'error': True, 'form': form})

    else:
        return render(request, 'Chef/ContactUs.html', {'form': ContactForm()})


def about_us(request):
    return render(request, 'Chef/About Us.html')

food/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from .models import Food
from django.db.models import Avg
from .forms import FoodDetailForm


def menu_food_view(request):
    foods_list = Food.objects.all()
    paginator = Paginator(foods_list, 16)
    try:
        page = int(request.GET.get('page', '1'))
    except:

        page = 1

    try:
        foods = paginator.page(page)

    except (EmptyPage, InvalidPage):
        foods = paginator.page(paginator.num_pages)
    return render(request, 'food/menu-list.html', {'food_list': foods})


def detail_food_view(request, rid, slug):
    food_id = Food.objects.get(id=rid)
    rating_value = request.POST.get('rating')
    print(rating_value)
    print(request.POST)
    if request.is_ajax() and request.POST:

        # rank = Food.objects.get_or_create(rating=data[rating_value])
        rank = Food.objects.filter(food_id).annotate(rank=Avg(rating_value))
        food_id.rating = rank
        food_id.rating.save()
        data = {
                     "rating": True
                 }

        return JsonResponse(data, status=200)

    else:
        return render(request, 'food/detail_food.html', {'food_detail': food_id})

#     # print(rating_value)
#     print(request.is_ajax)
#     print(request.POST)
#     if request.is_ajax() and request.POST:
#
#         initial_rating = Food.objects.get_or_create('rating')
#         rating_value = Food.objects.get(initial_rating).annotate(avg_rating=Avg(food_id.rating))
#         rank += rating_value
#
#         data = {
#             "rating": True
#         }
#
#         return JsonResponse(data, status=200)
#     else:
#         return render(request, 'food/detail_food.html', {'food_detail': food_id})


    # some error occured
    # return JsonResponse({"error": ""}, status=400)
        # return  message to save rating
    # elif request.ajax:
    #      data = {
    #          'message':"Ok"
    #      }
    #      return JsonResponse(data)

    #     # food_detail = request.POST.get(food_rating).annotate(rating=Av)
    #
    #
    #     return render(request, 'food/detail_food.html', {'food_detail': food_rating})
    # else:
    # return render(request, 'food/detail_food.html', {'food_detail': food_rating})


# def detail_food_view(request, rid, slug):
#     food_id = Food.objects.get(id=rid)
#     if request.POST:
#         rating_value = request.POST.get('rating')
#         form = FoodDetailForm(request.POST)
#         print(rating_value)
#         if form.is_valid():
#             data = form.cleaned_data(request.POST)
#             rank = Food.objects.get_or_create(rating=data[rating_value])
#             rank.save()
#             print(form)
#             rank = Food.objects.filter(food_id).annotate(rank=Avg(rating_value))
#             food_id.rating = rank
#             food_id.rating.save()
#             return render(request, 'food/done.html')
#         else:
#             return render(request, 'food/detail_food.html', {'form': form})
#     else:
#         return render(request, 'food/detail_food.html', {'food_detail': food_id})

Chef/templates/food/checkout_list.html
{% extends 'Chef/base.html' %}
{% load static %}


{% block slider %}
    <!--================Banner Area =================-->
        <section class="banner_area">
            <div class="container">
                <div class="banner_content">
                    <h4>Check Out List</h4>
                    <a href="#">Home</a>
                    <a class="active" href="#">Your Orders</a>
                </div>
            </div>
        </section>
    <!--================End Banner Area =================-->


    {% if request.session.foods %}
        <h3> List of your orders</h3>
        <form  id="checkout"  action="{% url 'food:checkout' %}" method="POST">{% csrf_token %}
            <table>
                <tr>
                    <td> # </td>
                    <td> name</td>
                    <td> price </td>
                    <td> quantity </td>
{#                    <td> Total </td>#}
                </tr>
                {% for food in request.session.foods %}
                <tr>
                    <td> <img src="{{ food.picture}}" style="height: 100px; width: 100px;"></td>
                    <td> {{ food.name }}</td>
                    <td> {{ food.price }}</td>
                    <td> {{ food.quantity }}</td>
                    <td>{% widthratio food.quantity 1 food.price %}</td>
                {% endfor %}

                </tr>
                <tr>
                    <td>
                    Subtotal:
                    </td>
                    <td> {{ request.session.subtotal }}</td>
                </tr>
                <tr>
                    <td>
                    Total:
                    </td>
                    <td> {{ request.session.total }}</td>
                </tr>
                <tr >
                        <td>
                            <input class="button" type="submit" name="save" value="save" onclick="check()"/>
                        </td>
                </tr>

            </table>
        </form>

        <script type="text/javascript">
            function check() {
                document.getElementById('checkout').submit()
                    alert("OK,save your orders!")
                    location.href="{% url 'food:menu_food' %}";
                    }
        </script>
    {% endif %}
{% endblock %}

Chef/templates/food/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  " Every thing is OK"
</body>
</html>

Chef/templates/food/menu-list.html
{% extends 'Chef/base.html' %}
{% load static %}


{% block slider %}

    <section class="banner_area">
            <div class="container">
                <div class="banner_content">
                    <h4>Menu List</h4>
                    <a href="#">Home</a>
                    <a class="active" href="menu-list.html">Menu</a>
                </div>
            </div>
    </section>

    <section class="most_popular_item_area menu_list_page">
            <div class="container">
                <div class="popular_filter">
                    <ul>
                        <li class="active" data-filter="*"><a href="">All</a></li>
                        <li data-filter=".PIZ"><a href="">Pizza</a></li>
                        <li data-filter=".BUR"><a href="">Burger</a></li>
                        <li data-filter=".SAN"><a href="">Sandwich</a></li>
                        <li data-filter=".FRI"><a href="">Fried</a></li>
                        <li data-filter=".SAL"><a href="">Salad</a></li>
                        <li data-filter=".APP"><a href="">Appetizer</a></li>
                    </ul>
                </div>
                <div class="p_recype_item_main">
                    <div class="row p_recype_item_active">
                        {% if food_list %}
                            {% for food in food_list %}
                                <form action="{% url 'food:add_to_cart' %}" method="POST">{% csrf_token %}
                                <div class="col-md-6 {{ food.category }}">
                                    <div class="media">
                                        <div class="media-left">
                                            <img src="{{ food.picture_food.url }}" width="120px" height="115px" alt="" />
                                        </div>
                                        <div class="media-body">
                                            <a href="#"><h3>{{ food.name }}</h3></a>
                                            <h4>${{ food.price }}</h4>

                                            <a href="{% url 'food:detail' food.name food.id %}"><p>More Info</p></a>
                                            <input  type="hidden" name="food-id" value="{{ food.id}}"/>
                                            <input id="#add_to_cart" class="read_mor_btn" type="submit" value="Add To Cart" />
{#                                            <a id="#add_to_cart" data-id="{{food.id}}" class="read_mor_btn" href="{% url 'food:cart'  %}">Add To Cart</a>#}
{#                                            <ul>#}
{#                                                <li><a href="#"><i class="fa fa-star"></i></a></li>#}
{#                                                <li><a href="#"><i class="fa fa-star"></i></a></li>#}
{#                                                <li><a href="#"><i class="fa fa-star"></i></a></li>#}
{#                                                <li><a href="#"><i class="fa fa-star"></i></a></li>#}
{#                                                <li><a href="#"><i class="fa fa-star-half-o"></i></a></li>#}
{#                                            </ul>#}
                                            <fieldset class="rating">
                                                <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                                                <input type="radio" id="star4half" name="rating" value="9/2" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
                                                <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
                                                <input type="radio" id="star3half" name="rating" value="7/2" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
                                                <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
                                                <input type="radio" id="star2half" name="rating" value="5/2" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
                                                <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
                                                <input type="radio" id="star1half" name="rating" value="3/2" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
                                                <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
                                                <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
                                            </fieldset>
                                        </div>

                                    </div>
                                </div>
                                </form>
                            {% endfor %}

                            <!--------------- Paginator ---------->
                            <div class="pagination">
                            <span class="step-links">
                                {% if food_list.has_previous%}
                                    <a href="?page={{ food_list.previous_page_number }}"> previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ food_list.number }}of{{ food_list.paginator.num_pages }}.
                                </span>

                                {% if food_list.has_next%}
                                    <a href="?page={{ food_list.next_page_number }}"> next </a>
                                {% endif %}
                            </span>
					        </div>


                        {% endif %}
                    </div>
                </div>
            </div>
        </section>
        <!--================End Our feature Area =================-->

{% endblock %}